### ISSUE TITLE
Error compile with C++98 standard

### ISSUE THREAD

**Issue by nicolas-gibelin** [lamyj/dicomifier#19]
By default, on my debian 8, the compile process fail with: 

... dicomifier/src/lib/core/Logger.h:28:1: error: in C++98 'dicomifier::level_dictionary' must be initialized by constructor, not by '{...}' };

you can solve this by adding in CMakeLists.txt:

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")

**Comment by lamyj** [comment]
Solved by 858459d. I also update the [compilation instructions](https://github.com/lamyj/dicomifier/wiki/Compiling)
