### ISSUE TITLE
Not Able to Use dicom2nifti

### ISSUE THREAD

**Issue by cecilyen** [lamyj/dicomifier#38]
I am using the RPM packages for CentOS 7. When I tried to use dicom2nifti on the DICOM files converted from bruker2dicom, it will not generate NiFTI files and give me following error messages.

dicom2nifti: error: Python argument types in odil._odil.as_unicode(unicode, Strings)
did not match C++ signature:
    as_unicode(std::string input, std::vector<std::string, std::allocator<std::string> > specific_character_set, bool is_pn=False)

**Comment by lamyj** [comment]
After looking everywhere for Unicode errors, I think I solved this: the CentOS 7 repository was out of date and contained version 1.2.0 instead of the latest 1.2.1 😞.

**Comment by cecilyen** [comment]
After updating to 1.2.1, dicom2nifit seems to work now. Thanks!
