### ISSUE TITLE
error. Help me

### ISSUE THREAD

**Issue by NicolaF899** [lamyj/dicomifier#40]
This is my error:

bruker2dicom convert --dicomdir Neat_pura_1_1_20190919_151114/24/pdata/1/                                                     
/usr/lib64/python2.7/site-packages/dicomifier/__init__.py:13: RuntimeWarning: to-Python converter for std::vector<int, std::allocator<int> > already registered; second conversion method ignored.                                                                                                      
  from . import bruker                                                                                                                              
usage: bruker2dicom convert [-h] [--reconstruction SERIES_AND_RECONSTRUCTIONS]
                            [--transfer-syntax TRANSFER_SYNTAX] [--multiframe]
                            [--dicomdir] [--verbosity {warning,info,debug}]
                            source destination
bruker2dicom convert: error: too few arguments

can someone help me?

**Comment by lamyj** [comment]
You are missing an argument on the command line: the destination directory. Your call to `bruker2dicom` should be something like:
```
bruker2dicom convert --dicomdir Neat_pura_1_1_20190919_151114/24/pdata/1/ Neat_pura_1_1_20190919_151114.dcm
```
where `Neat_pura_1_1_20190919_151114.dcm` is the directory where you want the DICOM files to be stored.

Also note that this will convert only one series (more precisely only one reconstruction), number 24 in your exam. You could do the same thing using the `-r` option:
```
bruker2dicom convert --dicomdir -r 24:1 Neat_pura_1_1_20190919_151114 Neat_pura_1_1_20190919_151114.dcm
```

This latter form is a bit more generic, as it will also work with Paravision archives (files with the `.PvDataset` suffix).
